#!/usr/bin/env node
// Bundles the reviewed kits/ into extension/catalog/registry.js, an importable module holding each
// catalog kit's manifest and its tool run functions. Catalog kit CODE ships in the extension package
// (no runtime fetch); this is what makes the store "remote code" answer "No".
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const kitsDir = path.join(root, "kits");
const out = path.join(root, "extension", "catalog");
fs.mkdirSync(out, { recursive: true });

const names = fs.readdirSync(kitsDir).filter((n) => fs.existsSync(path.join(kitsDir, n, "manifest.json")));
let body = "// AUTO-GENERATED by scripts/build-catalog.js — do not edit.\n\n";
const entries = [];
for (const name of names) {
  const manifest = JSON.parse(fs.readFileSync(path.join(kitsDir, name, "manifest.json"), "utf8"));
  const toolMap = [];
  for (const t of manifest.tools) {
    const file = t.file || `tools/${t.name}.js`;
    let src = fs.readFileSync(path.join(kitsDir, name, file), "utf8").trim();
    const fnName = `${name}__${t.name}`.replace(/[^A-Za-z0-9_]/g, "_");
    // pull the run body and wrap it so the injected function catches and reports errors as {__ok,...}
    const m = src.match(/async function run\s*\(args\)\s*\{([\s\S]*)\}\s*$/);
    if (!m) throw new Error(`${name}/${t.name}: expected 'async function run(args) { ... }'`);
    const runBody = m[1];
    body += `async function ${fnName}(args) {\n  try {\n    const __run = async () => {${runBody}};\n    const __v = await __run();\n    return { __ok: true, value: __v === undefined ? null : __v };\n  } catch (e) { return { __ok: false, error: (e && e.message) || String(e) }; }\n}\n\n`;
    toolMap.push(`    ${JSON.stringify(t.name)}: ${fnName},`);
  }
  entries.push(`  {\n    manifest: ${JSON.stringify(manifest)},\n    tools: {\n${toolMap.join("\n")}\n    },\n  },`);
}
body += `export const CATALOG = [\n${entries.join("\n")}\n];\n`;
fs.writeFileSync(path.join(out, "registry.js"), body);
console.log(`catalog bundled: ${names.join(", ")} -> extension/catalog/registry.js (${(body.length/1024).toFixed(1)}kb)`);
